apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weblab-ingress
  namespace: weblab
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: weblab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000